server:
  port: 9090
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/GALAXY?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
